version: '3'
services:
  app:
    container_name: talent_api
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - talent-postgres
    networks:
      - talent


  talent-postgres:
    image: postgres:latest
    container_name: talent_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - talent

volumes:
  api:
  database_postgres:

networks:
  talent:
    driver: bridge